garg3133/JagratiWebApp

templates/home/index.html
templates/snippets/footer.html

Auto year update added

---

static/home/css/style.css

Css update

---

templates/accounts/volunteer_profile.html
templates/home/dashboard.html

fetch date from django in dashboard 

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Kindly do check and merge it @garg3133 
Kindly do add the same labels add in the issue to pr also

CONTRIBUTING AND CODE OF CONDUCT FILE 

---

apps/students/models.py

Added a gender field in Student model of students app.

Added a gender field in Student model #35

---

templates/home/dashboard.html
templates/students/attendance.html
templates/volunteers/update_schedule.html
templates/volunteers/volunteers_list.html

The ajax calls have been modified to post requests from get

Updated the ajax calls to post

---

templates/accounts/login_signup.html

Update the email verifier.
Issue #57

Email checker Updated

---

static/home/css/style.css
templates/home/index.html

this PR modifies the contact icon on homepage. It resolves issue #55
@garg3133 kindly review.

modify contact icon

---

accounts/urls.py
accounts/views.py
templates/accounts/volunteer_profile.html

**Issue that resolved:**
https://github.com/garg3133/JagratiWebApp/issues/22
**Description of change:**
before adding data into the table, check for duplicacy on the roll number added. If the entered roll number has no conflict with the already existing roll number, we will proceed to make an entry in the table otherwise respective error will be displayed. check is added in `account/views.py` and error will be shown in `accounts/volunteer_profile.html`.

Integrity error on duplicate roll number have been resolved.

---

Jagrati/settings/base.py
Jagrati/urls.py
accounts/models.py
templates/accounts/login_signup.html

[Fixes #62] Added google authentication

---

.github/workflows/greetings.yml

Added Github Action/Welcome Bot for first time contributors to this project.
Fixes: #56 #86

Added github action

---

apps/students/urls.py
apps/students/views.py
templates/students/profile.html
templates/students/update_profile.html

@garg3133 I have create the form for updating student profile. This is in reference to issue #73
however I have some doubts:
* which fields are required
* which validations are needed 
Please review and let me know if there are other changes needed

add student profile update

---

templates/sidebar.html

Fixes: #41 
After clicking on the card

feat: Created a personal-info card on sidebar

---

.github/linters/.flake8.yml
.github/workflows/python_lint.yml

I have added a Flake8 Linter, as proof of its working, I will allow it to run on the whole codebase once, there will be a to of errors (hopefully not) considering you told me that there is no strict guideline.
Fixes #97
After that I will ensure that it runs on new PRs only, I can also make it to run on the pushes also in case you want me to do that.

Added Flake8 Linter

---

static/home/css/style.css
templates/home/index.html

Fixes: #100 
Added a scroll-to-top button in homepage.

Added scroll-to-top button

---

apps/students/models.py

Issue: #36 
Description: profile_image field added and used image kit to compress it before storing.

Dp to Student model added

---

static/home/js/myjs.js
templates/home/index.html

Related Issue - #126 
Fixes: 
- Fixed all typos 
- modified description of donate section.

Fixed typos regarding issue #126

---

templates/accounts/volunteer_profile.html
templates/students/new_student.html
templates/volunteers/update_profile.html

Fixes: 
- change 1
- change 2
- any additional information or context
** original screenshot **  |  ** updated screenshot **

Add checks for profile picture while uploading #121

---

apps/students/views.py

https://github.com/garg3133/JagratiWebApp/issues/118
- Remove the update button and make changes in the code accordingly.
- I thought that I have to mark absent for everyone while we load the page for the first time and later it will be handled by AJAX call but, It marks absent for everyone itself whoever scheduled at that date hence, I just remove the code for form submission.

Remove code that mark attendance

---

README.md

Fixes: #147 
- added logo  of tech stack below their names

Added Tech stack Logo 

---

home/models.py
home/views.py
templates/home/dashboard.html

Made a completely new PR after refactoring as guided by mentor.

Display subject on dashboard.

---

apps/misc/admin.py
apps/misc/forms.py
apps/misc/models.py

Fixes: #14 
- added initiative model
- did not change views.py or index.html(as per instructions)

store initiatives in the database

---

templates/registration/password_change_form.html

Fixes:  #182 
- Changed UI of Password Change form ( fix #182)
|

Changed UI of Password Change form

---

templates/registration/password_reset_complete.html

Fixes: #182  
-  Changed the UI of Password reset complete page

Update UI of Password Reset Complete Page

---

README.md

Fixed #114
Fixes: #114 
- Add the following OSS events in README.md
* Kharagpur Winter of Code 2020
* Script Winter of Code 2021
* Mexili Winter of Code 2021
* GirlScript Summer of Code 2021

Updated README.md by adding OSS events

---

templates/registration/password_reset_done.html

Fixes: #182 
- Changed UI of Password reset done page
|

change UI of password reset done

---

templates/registration/password_change_done.html

- Changed UI of password_change_done.html

UI changes to password_change_done.html

---

apps/students/urls.py
apps/students/views.py
templates/home/dashboard.html

Fixes: #175 
- Added `ajax_mark_homework()` in `students/views.py`, it marks if student has submitted button.
- If the state of toggle has been changed a JQuery function is invoked and ajax POST request is sent to above function and it does required changes to Model.
- Added Cookie Library in dashboard.html to fetch csrftoken from Cookies to perform AJAX Request.

Created Homework Check Toggle Button

---

static/new_home/style.css
templates/new_home/index.html

Fixes: #215 
- Use of grid template areas
- Media queries
- any additional information or context
** original screenshot **  |  ** updated screenshot **

About us section grid fixed

---

static/new_home/style.css
templates/new_home/contact.html

Fixes: #216 
- Added display grid to the bootstrap column cards 

Fixed contact section card behaving absurdly on responsive

---

apps/volunteers/views.py
templates/volunteers/profile.html

Fixes: #240 
- Add schedule for volunteers in the form of a table in the profile section

Added schedule table in volunteer profile page

---

Jagrati/settings/base.py
accounts/views.py

Fixed: #58
- We can implement our own password validator for more strong password/custom password.
- Currently used django core password validator.
Updated
:-------------------------:
** updated screenshot **

Password validator added in signup

---

templates/home/dashboard.html
templates/home/index.html
templates/new_home/index.html

Fixes:   #221  
- Removed excess tags and outdated properties.
- Added alt tags to images

HTML Validation

---

templates/registration/password_reset_confirm.html

Fixes: #182 
- Changed pasword_reset_confirm.html\

Changed password_reset_confirm.html

---

templates/students/update_profile.html

Fixes: #174 
- Added camera overlay when hovered over the student's profile photo.

camera overlay added to the student's profile

---

accounts/tests/test_views.py

closes issue #76 
Wrote unit tests for login_signup view in the accounts app. The tests are added in a file test_views in test directory of accounts app and tested it written in django

written unit-tests for login_signup view in django

---

static/home/css/style.css
templates/home/index.html

Fixes: #257 
- change 1 :  Added the icons in the donate section
- change 2 :  Added direct links to the email ids present for better user experience
Kindly review it. Thank you

links and icons added in home page

---

templates/volunteers/update_profile.html

Fixes: 
Update Profile section has Roll No type 'number'
- Change roll no type to 'text'

changed the roll no type to text on update page

---

.gitignore
accounts/admin.py
apps/volunteers/urls.py
apps/volunteers/views.py
templates/sidebar.html
templates/volunteers/leaderboard.html

Fixes: Add Volunteer Leaderboard
- Added an attendance leaderboard for volunteers

Leaderboard created

---

apps/volunteers/views.py
templates/volunteers/leaderboard.html

Fixes: Serial Number, Sequencing Refinements
- Add serial number column in the leaderboard table
- Add sequencing by extra days as secondary parameter in the sequencing algorithm

serial number, sequencing refinements

---

apps/students/urls.py
apps/students/views.py
templates/sidebar.html
templates/students/leaderboard.html

Fixes: Student Leaderboard
- Create a student leaderboard to track student's attendance in the past 30 days

Student Leaderboard Created

---

templates/students/attendance.html

Fixes: #307 
- 'All Students' option on Student Attendance Page.

All Option on Student Attendance Class DropDown
